wand:
  material: BLAZE_ROD
  name: "<gradient:#FFAA00:#FFFF55>Sell Wand</gradient>"
  custom-model-data: 0
  default-uses: 100
  default-multiplier: 1.0
  lore:
    - ""
    - "<gray>Right-click a container to sell items.</gray>"
    - ""
    - "<yellow>Uses:</yellow> <white>%uses%</white>"
    - "<yellow>Multiplier:</yellow> <white>%multiplier%x</white>"

settings:
  check-container-permissions: true
  remove-on-use-up: true
  multiplier-mode: ADD # can only be "ADD" or "MULTIPLY", will default to "MULTIPLY"

containers:
  - CHEST
  - TRAPPED_CHEST
  - BARREL
  - HOPPER
  - DROPPER
  - DISPENSER
  - FURNACE
  - BLAST_FURNACE
  - SMOKER
  - BREWING_STAND
  - ENDER_CHEST
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - LIME_SHULKER_BOX
  - PINK_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - RED_SHULKER_BOX
  - BLACK_SHULKER_BOX
